In [2]:
import numpy
from pyscf import gto, scf, df

In [4]:
mol_h2 = gto.M(atom='h 0 0 0; h 0 0 0.741', basis='sto3g')
mol_heh = gto.M(atom='he 0 0 0; h 0 0 0.741', charge=1, basis='sto3g')
mol_li2 = gto.M(atom='li 0 0 0; li 0 0 0.741', basis='sto3g')

In [5]:
# '[atom number in molecule] [atom] [atomic orbital]'
print("atoms and associated atomic orbitals:", mol_h2.ao_labels())

# nbas: number of shells (counts 2px, 2py, 2pz as one)
print("number of shells:", mol_h2.nbas)

# nao: number of atomic orbitals
print("number of atomic orbitals:", mol_h2.nao)

atoms and associated atomic orbitals: ['0 H 1s    ', '1 H 1s    ']
number of shells: 2
number of atomic orbitals: 2


In [11]:
myhf = scf.HF(mol_heh)
myhf.kernel()

converged SCF energy = -2.83410218317347


-2.8341021831734654

In [12]:
mol = mol_heh
# One body integrals: E = T + U
one_body = mol.intor('int1e_kin_sph') + mol.intor('int1e_nuc_sph')

# Atomic orbital overlap?
# overlap = mol.intor('int1e_ovlp_sph')

# Two body integrals: electron repulsion integrals
eri = mol.intor('int2e_sph')


In [13]:
print(one_body)

[[-2.62477917 -1.50839758]
 [-1.50839758 -1.77403912]]


In [14]:
# print(overlap)

In [15]:
print(eri)

[[[[1.05571294 0.46784056]
   [0.46784056 0.6063442 ]]

  [[0.46784056 0.24654644]
   [0.24654644 0.38853706]]]


 [[[0.46784056 0.24654644]
   [0.24654644 0.38853706]]

  [[0.6063442  0.38853706]
   [0.38853706 0.77460594]]]]
